import type { Person, Loan, Payment, Transaction } from '../types';

export const seedPeople: Person[] = [
  { id: 'p-vijay', name: 'Vijay Kumar' },
  { id: 'p-manoj', name: 'Manoj Iyer' },
  { id: 'p-priya', name: 'Priya Nair' },
  { id: 'p-asha', name: 'Asha Reddy' },
];

export const seedLoans: Loan[] = [
  {
    id: 'l-vijay-1',
    personId: 'p-vijay',
    direction: 'given',
    principal: 30000,
    dateGiven: '2026-09-10',
    interestRatePctPerMonth: 2,
    promisedReturnDate: '2026-12-10',
    nickname: 'VK-30K',
    status: 'active',
    notes: "Given for his shop's stock purchase, near Anna Nagar. Handed over in cash.",
    paymentMode: 'Cash',
  },
  {
    id: 'l-vijay-2',
    personId: 'p-vijay',
    direction: 'given',
    principal: 80000,
    dateGiven: '2026-09-15',
    interestRatePctPerMonth: 1.5,
    nickname: 'VK-80K',
    status: 'active',
    notes: 'Second, separate loan a week after the first — for a family function. Sent via GPay.',
    paymentMode: 'Google Pay',
  },
  {
    id: 'l-manoj-1',
    personId: 'p-manoj',
    direction: 'given',
    principal: 15000,
    dateGiven: '2026-03-15',
    interestRatePctPerMonth: 3,
    promisedReturnDate: '2026-09-04',
    status: 'active',
    notes: 'Keeps saying "next week" — third time now. Given for his son\'s school fees, by hand.',
    paymentMode: 'Cash',
  },
  {
    id: 'l-priya-1',
    personId: 'p-priya',
    direction: 'given',
    principal: 100000,
    dateGiven: '2026-07-02',
    interestRatePctPerMonth: 2,
    status: 'active',
    notes: 'Regular payer, always pays interest on the 25th. Bank transfer each time.',
    paymentMode: 'Bank transfer',
  },
  {
    id: 'l-asha-1',
    personId: 'p-asha',
    direction: 'taken',
    principal: 50000,
    dateGiven: '2026-01-05',
    interestRatePctPerMonth: 1,
    status: 'active',
    notes: 'Borrowed to cover a medical bill. Paid to his account directly.',
    paymentMode: 'Bank transfer',
  },
];

export const seedPayments: Payment[] = [
  {
    id: 'pay-manoj-1',
    loanId: 'l-manoj-1',
    date: '2026-06-02',
    totalAmount: 450,
    principalPortion: 0,
    interestPortion: 450,
    paymentMode: 'Cash',
    notes: 'Interest only',
  },
  {
    id: 'pay-priya-1',
    loanId: 'l-priya-1',
    date: '2026-07-25',
    totalAmount: 2000,
    principalPortion: 0,
    interestPortion: 2000,
    paymentMode: 'Bank transfer',
    notes: 'Interest only',
  },
  {
    id: 'pay-priya-2',
    loanId: 'l-priya-1',
    date: '2026-08-25',
    totalAmount: 2000,
    principalPortion: 0,
    interestPortion: 2000,
    paymentMode: 'Bank transfer',
    notes: 'Interest only',
  },
];

export const seedTransactions: Transaction[] = [
  {
    id: 'txn-1',
    date: '2026-09-02',
    type: 'credit',
    amount: 450,
    category: 'Interest income',
    paymentMode: 'Cash',
    title: 'Manoj Iyer',
  },
  {
    id: 'txn-2',
    date: '2026-09-14',
    type: 'debit',
    amount: 2100,
    category: 'Utilities',
    paymentMode: 'PhonePe',
    title: 'Electricity bill',
  },
  {
    id: 'txn-3',
    date: '2026-09-16',
    type: 'debit',
    amount: 120,
    category: 'Household',
    paymentMode: 'Cash',
    title: 'Tea & snacks',
  },
  {
    id: 'txn-4',
    date: '2026-09-18',
    type: 'debit',
    amount: 1850,
    category: 'Clothing',
    paymentMode: 'Google Pay',
    title: "New shirt for Rahul's function",
  },
  {
    id: 'txn-5',
    date: '2026-09-21',
    type: 'debit',
    amount: 4600,
    category: 'Household',
    paymentMode: 'Cash',
    title: 'Grocery — monthly',
  },
  {
    id: 'txn-6',
    date: '2026-09-25',
    type: 'credit',
    amount: 2000,
    category: 'Interest income',
    paymentMode: 'Bank transfer',
    title: 'Priya Nair',
  },
];
